import logo from './logo.svg';
import './App.css';
import Nani from './components/Nani';

function App() {
  return (
    <div className="App">
      <h1>NANI Movies List</h1>
      <div className='movieDiv'>
        <img src="https://upload.wikimedia.org/wikipedia/en/a/a1/Ashta_Chamma_Poster.JPG" alt=""></img>
        <h3>Movie Name:Ashta Chamma</h3>
        <h3>Year:2008</h3>
        <h3>Story line: Ashta Chamma (2008) is a Telugu romantic comedy that revolves around Lavanya (Colors Swathi), who is a huge fan of actor Mahesh Babu. Disappointed upon learning about his marriage, she decides to marry someone with the same name, "Mahesh." Lavanya soon meets a man (Srinivas Avasarala) who introduces himself as Mahesh, and they start a relationship. However, it turns out his real name is Anand, leading to a series of comedic misunderstandings. As the truth unravels, the film explores the evolving relationships between the characters, filled with humor, witty dialogue, and romance. The movie is a fun, light-hearted take on love and identity.</h3>
      </div>
      <div className='movieDiv'>
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQu9sThD9vr41vKG1eWI8D0xxGumLfd9ReuXA&s" alt=""></img>
        <h3>Movie Name:Ride</h3>
        <h3>Year:2009</h3>
        <h3>Story line: Ride (2009) is a Telugu action-comedy that follows the lives of two young men, Arjun (Nani) and Mahesh (Tanish). Arjun is an ambitious but unemployed youth who is desperate to find a job, while Mahesh is a carefree guy who takes life lightly. Their paths cross when Arjun's bike, which he values greatly for his job prospects, is stolen by Mahesh, who uses it for his own fun. This leads to a series of comedic and dramatic events as they constantly clash over the bike. However, as the story progresses, both men learn important life lessons, form an unlikely bond, and discover the value of hard work and friendship. The movie blends humor, action, and emotions, making it an entertaining watch.</h3>
      </div>

      <Nani MovieName="Snehithuda" Year="2009" StoryLine="Snehithuda (2009) is a Telugu romantic drama that stars Nani and Maadhavi Latha. The story revolves around Sai (Nani), a kind-hearted and carefree young man who meets Savitri (Maadhavi Latha), a girl in distress. Savitri has run away from home due to a misunderstanding with her family. Sai offers her shelter and support, and they develop a strong bond of friendship. However, as they navigate through the challenges of clearing up Savitri's family issues, Sai gradually falls in love with her. The film explores themes of friendship, love, and family misunderstandings, with a focus on emotional drama and the growing relationship between the lead characters." picURL="https://images.plex.tv/photo?size=large-1280&url=https%3A%2F%2Fmetadata-static.plex.tv%2Fd%2Fgracenote%2Fd9cec6d4c9c95b1fe0bb63a750af9177.jpg"></Nani>

      <Nani MovieName="Bheemili Kabaddi Jattu" Year="2010" StoryLine="Bheemili Kabaddi Jattu (2010) is a Telugu sports drama about Suri (Nani), a shy young man from the small village of Bheemili who is passionate about Kabaddi. Despite the local team's lack of experience and resources, they are determined to compete in a state-level Kabaddi tournament. The story follows their journey as underdogs, facing intense challenges and emotional struggles, while Suri also develops a romantic interest in Saranya (Saranya Mohan). The film highlights themes of perseverance, teamwork, and sacrifice, leading to an emotional and powerful climax as the team strives to achieve their dream against all odds." picURL="./images/bhemili.jpg"></Nani>

      <Nani MovieName="Ala Modalaindi" Year="2011" StoryLine="Ala Modalaindi (2011) is a romantic comedy about the unpredictable love story of Gautham (Nani) and Nithya (Nithya Menen). The movie begins with Gautham being kidnapped and narrating his love story to his captor. He explains how he first met Nithya at a time when he was heartbroken over his ex-girlfriend's marriage. What starts as a series of funny and coincidental encounters between Gautham and Nithya leads to a close friendship. However, both keep missing their chances to confess their love due to misunderstandings and timing issues, and they get involved with other people along the way. The movie is filled with humorous twists and emotional moments as the two realize their true feelings for each other. It’s a light-hearted, feel-good film about fate, relationships, and the journey to finding love." picURL="./images/ala.jpg"></Nani>

      <Nani MovieName="Veppam" Year="2011" StoryLine="Veppam (2011) is a Tamil action-drama film that revolves around the lives of three friends—Karthik (Karthik Kumar), a hardworking youth with dreams of a better life; Vimal (Vimal), a carefree individual; and Vennila (Nani), who is caught in a web of personal struggles. The story unfolds in a gritty urban backdrop, showcasing the challenges they face due to poverty, crime, and betrayal. As Karthik strives to escape the harsh realities of his environment, he becomes entangled in a series of events that lead to conflict with local criminals. The film explores themes of friendship, love, and survival while highlighting the impact of choices made in desperate circumstances. With a blend of action and emotional depth, Veppam delves into the characters’ struggles and their quest for redemption." picURL="./images/veppam.jpg"></Nani>

      <Nani MovieName="Pilla Zamindar" Year="2011" StoryLine="Pilla Zamindar (2011) is a Telugu romantic comedy that follows Dhanunjay (Nani), a carefree young man and heir to a wealthy zamindar family. After his grandfather's death, he is called back to his ancestral village to claim his inheritance, but he must first fulfill certain conditions to prove his worthiness. As he grapples with the responsibilities of managing the estate and caring for the villagers, Dhanunjay meets and falls in love with Kalyani (Priya Anand), a spirited local girl. The film explores Dhanunjay's journey from a carefree youth to a responsible leader as he learns to connect with the villagers and overcome various challenges. With a blend of humor, romance, and heartfelt moments, Pilla Zamindar emphasizes themes of love, community, and personal growth." picURL="./images/pillazamindar.jpg"></Nani>

      <Nani MovieName="Eega" Year="2012" StoryLine="Eega (2012) is a unique fantasy action film directed by S. S. Rajamouli that tells the story of a man who is reincarnated as a housefly after being killed by a ruthless businessman named Sudeep. The protagonist, Nani, is deeply in love with a beautiful woman named Bindu (Samantha Ruth Prabhu). After his untimely death at the hands of Sudeep, Nani is reborn as a fly, determined to take revenge on his murderer and protect Bindu. Utilizing his newfound abilities, Nani creatively devises plans to torment Sudeep and save Bindu from his clutches. The film blends action, humor, and romance in a captivating narrative that showcases the resilience of love even beyond death. Eega received critical acclaim for its innovative storyline, visual effects, and unique concept, making it a memorable addition to Indian cinema." picURL="./images/eega.jpg"></Nani>

      <Nani MovieName="Yeto Vellipoindi Manasu" Year="2012" StoryLine="Yeto Vellipoindi Manasu (2012) is a Telugu romantic drama that revolves around Karthik (Nani) and Neetu (Samantha Ruth Prabhu), a young couple who fall in love during their college days. As they transition into adulthood, their passionate relationship is tested by misunderstandings, familial pressures, and personal ambitions. Karthik is portrayed as driven and ambitious, while Neetu embodies a free-spirited and independent nature. The film explores their emotional struggles and the impact of their choices on their love story, ultimately questioning whether true love can withstand the trials of life. With its engaging narrative and melodious soundtrack, Yeto Vellipoindi Manasu beautifully captures the essence of young love and the bittersweet experiences that come with it." picURL="./images/yetovelipoindi.jpg"></Nani>

      <Nani MovieName="Paisa" Year="2014" StoryLine="Paisa (2014) is a Telugu romantic action thriller that follows the story of a young man named Nani (Nani) who aspires to become rich and improve his family's financial situation. The film takes a twist when Nani discovers a large sum of money hidden in a suitcase, which leads him into the underworld of crime and corruption. As he navigates this dangerous world, he becomes entangled with powerful figures and faces moral dilemmas that test his values and relationships. The story explores themes of ambition, greed, and the consequences of one’s choices, all while blending romance and action. Ultimately, Paisa highlights the impact of wealth on personal relationships and the lengths one will go to achieve their dreams." picURL="./images/paisa.jpg"></Nani>

      <Nani MovieName="Aaha Kalyanam" Year="2014" StoryLine="Aaha Kalyanam (2014) is a Telugu romantic comedy that revolves around the lives of two young individuals, Shakthi (Nani) and Vani (Kajal Aggarwal), who come from different backgrounds but are brought together by the world of wedding planning. Shakthi, a wedding planner, is determined to make his mark in the industry, while Vani is a traditional girl who values family and culture. Their paths cross when they are assigned to organize a grand wedding, leading to a series of humorous and romantic escapades. As they navigate the challenges of planning the event, Shakthi and Vani develop a strong bond, leading them to confront their feelings for each other. The film beautifully blends comedy, romance, and the cultural significance of weddings, ultimately exploring themes of love, commitment, and the joy of celebrating relationships." picURL="./images/ahakalyanam.jpg"></Nani>

      <Nani MovieName="Yevade Subramanyam" Year="2015" StoryLine="Yevade Subramanyam (2015) is a Telugu coming-of-age drama that follows the journey of Subramanyam (Nani), a focused and ambitious young man who is dedicated to his corporate career. However, his life takes a transformative turn when he embarks on a trip to the Himalayas to fulfill his dying grandfather's wish. Accompanied by his childhood friend, the trip forces Subramanyam to confront his rigid mindset and reassess his priorities in life. Along the way, he discovers the beauty of nature, the value of relationships, and the importance of pursuing true happiness. The film beautifully explores themes of self-discovery, adventure, and the pursuit of dreams, making it a heartfelt narrative about breaking free from societal expectations and embracing life's adventures." picURL="./images/yevade.jpg"></Nani>

      <Nani MovieName="Janda Pai Kapiraju" Year="2015" StoryLine="Janda Pai Kapiraju (2015) is a Telugu action-drama film that tells the story of Karthik (Nani), a young man who becomes disillusioned with the injustices of society after a series of personal tragedies. Frustrated by the corruption and the struggles faced by common people, Karthik adopts the persona of a vigilante, Janda Pai Kapiraju, to fight against societal evils and protect the innocent. The film unfolds as Karthik takes on powerful adversaries, revealing his internal conflict between seeking revenge and upholding justice. With a mix of action, drama, and romance, the film explores themes of morality, the consequences of one’s choices, and the fight for justice, ultimately highlighting the impact one individual can have in a corrupt world." picURL="./images/jandapai.jpg"></Nani>

      <Nani MovieName="Bhale Bhale Magadivoy" Year="2015" StoryLine="Bhale Bhale Magadivoy (2015) is a Telugu romantic comedy that centers around the life of Venkatesh (Nani), a lovable yet absent-minded young man who struggles with his forgetfulness. His condition leads to humorous situations and complications, especially in his personal life. When Venkatesh falls in love with a beautiful woman named Nandini (Lavanya Tripathi), he tries to win her heart while managing his forgetful nature. As their relationship develops, Venkatesh's quirky antics and misunderstandings create a series of comedic events, especially when his forgetfulness complicates his interactions with Nandini’s family. The film cleverly blends romance, humor, and a touch of drama, ultimately highlighting the importance of love and understanding in overcoming life's challenges." picURL="./images/bhalebhale.jpg"></Nani>

      <Nani MovieName="Krishna Gaadi Veera Prema Gaadha" Year="2016" StoryLine="Krishna Gaadi Veera Prema Gaadha (2016) is a Telugu romantic comedy that follows the story of Krishna (Nani), a jovial and carefree young man living in a small village. He is deeply in love with a beautiful girl named Radha (Madhyama Reddy), who is unaware of his feelings. Krishna’s life takes an unexpected turn when he inadvertently gets involved in a feud with a local gangster, leading to a series of comical yet dangerous situations. As he tries to protect Radha and his village from the gangster's wrath, Krishna discovers his inner strength and bravery. The film blends romance, action, and comedy, showcasing themes of love, friendship, and courage in the face of adversity, ultimately delivering an entertaining narrative filled with heartfelt moments and laughter." picURL="./images/krishnagaadi.jpg"></Nani>

      <Nani MovieName="Gentleman" Year="2016" StoryLine="Gentleman (2016) is a Telugu romantic thriller that revolves around Gautham (Nani), a charming and suave young man who leads a double life. By day, he is a successful software engineer with a respectable demeanor, but by night, he is a cunning con artist involved in a series of heists. As Gautham juggles his dual identities, he becomes romantically entangled with two women, Chandini (Niveda Thomas) and Priya (Aditi Rao Hydari), each representing different facets of his life. The plot thickens when his past catches up with him, leading to suspenseful twists and unexpected revelations. The film explores themes of love, betrayal, and the consequences of one's choices, combining romance and action with a gripping narrative that keeps the audience engaged until the very end." picURL="./images/gentleman.jpg"></Nani>

      <Nani MovieName="Majnu" Year="2016" StoryLine="Majnu (2016) is a Telugu romantic drama that tells the story of a charming and carefree young man named Vikram (Nani), who is known for his love for women and his playful nature. However, his life takes a serious turn when he falls deeply in love with a beautiful and ambitious girl named Kiran (Anu Emmanuel). As their relationship blossoms, Vikram’s commitment to Kiran is tested by misunderstandings and complications that arise from their differing life goals. The film skillfully weaves elements of romance, comedy, and drama, showcasing Vikram's journey of self-discovery as he learns the true meaning of love, sacrifice, and responsibility. With its engaging storyline and emotional depth, Majnu captures the essence of youthful love and the challenges that come with it." picURL="./images/majnu.jpg"></Nani>

      <Nani MovieName="Nenu Local" Year="2017" StoryLine="Nenu Local (2017) is a Telugu romantic comedy that follows the story of Babu (Nani), a carefree and fun-loving young man who lives life on his own terms. He has a knack for getting into trouble but is also known for his charm and wit. Babu falls in love with Keerthi (Keerthy Suresh), a focused and ambitious girl who aspires to achieve great things in life. As he pursues her, Babu finds himself in a series of humorous and chaotic situations, especially when he inadvertently clashes with Keerthi's strict father, who disapproves of their relationship. The film explores themes of love, ambition, and the balance between personal dreams and relationships, all while delivering plenty of laughs and heartwarming moments, ultimately showcasing Babu's transformation from a local boy to someone who understands the importance of responsibility in love." picURL="./images/nenulocal.jpg"></Nani>

      <Nani MovieName="Ninnu Kori" Year="2017" StoryLine="Ninnu Kori (2017) is a Telugu romantic drama that revolves around the story of Uma (Nani) and his love for his college sweetheart, Pallavi (Aadhi Pinisetty). After a passionate relationship, Pallavi decides to marry someone else, leaving Uma heartbroken. Years later, Uma finds solace in his music and attempts to move on with his life. However, fate brings him back into Pallavi's life when she seeks his help during a challenging time. The film beautifully captures the complexities of love, sacrifice, and the impact of past relationships on the present. As the characters navigate their emotions, the narrative unfolds with heartfelt moments, music, and the realization that true love may not always lead to a happily ever after. Ninnu Kori explores themes of longing, emotional resilience, and the bittersweet nature of love." picURL="./images/ninnukori.jpg"></Nani>

      <Nani MovieName="MCA (Middle-Class Abbayi)" Year="2017" StoryLine="MCA (Middle-Class Abbayi) (2017) is a Telugu romantic comedy that follows the story of Nani (Nani), a middle-class man who is known for his simplicity and strong values. He lives with his loving family and dreams of a comfortable life. However, things take a turn when he falls in love with a spirited and independent girl named Pallavi (Bhoomika Chawla). As their relationship blossoms, Nani's laid-back approach to life clashes with the challenges of romance, family expectations, and societal pressures. The film skillfully blends humor, romance, and action, highlighting the struggles of a middle-class man as he strives to balance his personal aspirations and responsibilities. With its engaging storyline, lively performances, and a catchy soundtrack, MCA captures the essence of love and the trials of a middle-class life while delivering an entertaining experience." picURL="./images/mca.jpg"></Nani>

      <Nani MovieName="Krishnarjuna Yudham" Year="2018" StoryLine="Krishnarjuna Yudham (2018) is a Telugu action-comedy film that follows the adventurous journey of two distinct characters, Krishna (Nani) and Arjun (also Nani), who represent different sides of the same man. Krishna is a carefree and fun-loving youth living in a small village, while Arjun is a serious and committed army officer. The story takes a turn when Krishna learns that Arjun is in danger due to a mission involving a powerful villain. To save him and protect their loved ones, Krishna sets out on a thrilling journey that leads to comedic situations and intense action sequences. The film explores themes of brotherhood, love, and the contrasting aspects of human nature, delivering an entertaining blend of humor, romance, and action, while showcasing Nani's versatility in portraying dual roles." picURL="./images/krishnaarjuna.jpg"></Nani>

      <Nani MovieName="Devadas" Year="2018" StoryLine="Devadas (2018) is a Telugu romantic drama featuring Nani and Nagarjuna in lead roles, along with Rashmika Mandanna and Aakanksha Singh as the female leads. Nagarjuna portrays Devadas, a wealthy and charming man who spirals into alcoholism following personal losses, while Nani plays Dasu, a young, ambitious man who aspires to change his life circumstances. Rashmika Mandanna plays the role of a lively and supportive character who brings joy to Dasu's life, adding a vibrant dynamic to the story. Aakanksha Singh portrays the love interest of Devadas, providing a contrasting perspective on love and relationships. As the story unfolds, the interactions between these characters explore themes of friendship, love, and the struggles of overcoming personal demons. The film combines humor, emotional depth, and engaging performances, highlighting the transformative power of love and companionship in the face of adversity." picURL="./images/devdaas.jpg"></Nani>

      <Nani MovieName="Jersey" Year="2019" StoryLine="Jersey (2019) is a Telugu sports drama that tells the inspiring story of Arjun (Nani), a talented but disheartened cricketer who gave up his dreams of playing for the Indian national team due to personal setbacks and family pressures. Years later, struggling to provide for his family and facing a midlife crisis, Arjun decides to return to cricket at the age of 36, inspired by his son’s desire to see him succeed. The film beautifully explores Arjun's journey of self-discovery as he trains hard to regain his skills, confronts his past failures, and battles societal expectations. With a powerful narrative that highlights themes of determination, sacrifice, and the bond between a father and son, Jersey captures the essence of pursuing one's dreams, no matter the age or circumstances. The film is lauded for its emotional depth and Nani's compelling performance, making it a poignant tale of resilience and hope." picURL="./images/jersey.jpg"></Nani>

      <Nani MovieName="Gang Leader" Year="2019" StoryLine="Gang Leader (2019) is a Telugu action-comedy film featuring Nani as the lead character, Pencil Parthasarathy, a successful writer who finds himself unexpectedly drawn into the world of crime. The story begins when a group of women, seeking revenge for a loved one’s death, approach Parthasarathy for help. Initially reluctant, he is soon pulled into their plan to take down a ruthless gangster. As he joins forces with the group, each woman brings her own unique skills and quirks, leading to a mix of humor and action. The film combines elements of comedy, drama, and thrill, showcasing Parthasarathy's transformation from a peaceful writer to a resourceful leader. With its engaging storyline, witty dialogues, and strong performances, Gang Leader delivers a message about empowerment and camaraderie, all while entertaining the audience with its lively pace and clever twists." picURL="./images/gangleader.jpg"></Nani>

      <Nani MovieName="V" Year="2020" StoryLine="V (2020) is a Telugu action thriller featuring Nani in a dual role as Vikram, a charismatic criminal, and Sudheer Babu as Aditya, a principled police officer determined to stop him. The film follows Vikram's quest for revenge against those who betrayed him, leading to an intense battle of wits and action between the two characters. Aditi Rao Hydari plays a crucial role as the love interest of Aditya, adding emotional depth to the narrative. Her character provides a supportive and grounding presence, emphasizing the personal stakes involved in the conflict. The film skillfully blends suspense, action, and romance, showcasing themes of justice and the complexities of human relationships. With stylish cinematography and gripping storytelling, V keeps audiences engaged while exploring the moral dilemmas faced by its characters, ultimately highlighting the thin line between good and evil." picURL="./images/v.jpg"></Nani>

      <Nani MovieName="Tuck Jagadish" Year="2021" StoryLine="Tuck Jagadish (2021) is a Telugu family drama that centers around Jagadish (Nani), a kind-hearted and strong-willed man who values family above all else. When a conflict arises within his family due to property disputes, Jagadish is determined to resolve the issues and protect his loved ones. As he navigates the challenges posed by rival factions and internal strife, he also faces the emotional turmoil of dealing with relationships and expectations. Ritu Varma plays the role of his love interest, who brings warmth and support to Jagadish’s life, adding a romantic angle to the narrative. Their relationship develops amidst the family drama, highlighting themes of love, loyalty, and the importance of family bonds. The film combines action and emotional depth, showcasing Jagadish's journey as he fights to restore harmony in his family while also dealing with his personal aspirations and responsibilities." picURL="./images/tuck.jpg"></Nani>

      <Nani MovieName="Shyam Singha Roy" Year="2021" StoryLine="Shyam Singha Roy (2021) is a Telugu supernatural thriller that tells the story of Vasu (Nani), a struggling filmmaker who becomes entangled in a series of mysterious events after he experiences vivid dreams of a past life. The narrative takes a captivating turn when Vasu discovers that he shares a connection with a character named Shyam Singha Roy, a passionate artist from the 1970s. The film explores themes of love, sacrifice, and the impact of art on society as Vasu attempts to uncover the truth about his past and the injustices faced by Shyam. Alongside him, Sai Pallavi plays a pivotal role as a strong-willed woman who becomes integral to Vasu's journey, adding emotional depth and complexity to the storyline. With its rich visuals, engaging plot twists, and strong performances, Shyam Singha Roy captivates audiences, blending romance and supernatural elements while addressing societal issues and the power of love across lifetimes." picURL="./images/shyam.jpg"></Nani>

      <Nani MovieName="Ante Sundaraniki" Year="2022" StoryLine="Ante Sundaraniki (2022) is a Telugu romantic comedy that follows the quirky and entertaining love story of Sundar (Nani), a carefree and easy-going man who leads a simple life. Sundar falls in love with a strong-willed and independent woman named Nandini (Nazriya Nazim), who hails from a traditional family. As their relationship develops, they face numerous challenges due to their contrasting backgrounds and family expectations. The film explores themes of love, cultural differences, and the struggle to maintain individuality in a relationship. With its humorous dialogue, vibrant performances, and relatable situations, Ante Sundaraniki effectively captures the essence of modern romance while delivering a lighthearted yet meaningful narrative that highlights the importance of understanding and acceptance in love." picURL="./images/ante.jpg"></Nani>

      <Nani MovieName="Dasara" Year="2023" StoryLine="Dasara (2023) is a Telugu action drama set in a coal mining village, centering on the life of Dasara (Nani), a passionate and fiercely loyal young man deeply connected to his community. The narrative follows Dasara as he navigates the challenges posed by local politics and gang rivalries, especially after he becomes involved in a violent conflict while trying to protect his loved ones. Keerthy Suresh plays the role of his love interest, who adds emotional depth to the story and serves as Dasara's anchor amid the turmoil. Their relationship highlights themes of love and sacrifice, as she stands by him during his struggles. With its gripping plot, intense performances, and rich visuals, Dasara showcases the journey of a man who fights against injustice while exploring the complexities of love and loyalty in a backdrop filled with tradition and conflict." picURL="./images/dasara.jpg"></Nani>

      <Nani MovieName="Hi Nanna" Year="2023" StoryLine="Hi Nanna (2023) is a Telugu family drama that beautifully explores the profound bond between a devoted father, played by Nani, and his young daughter. The story follows this loving father as he navigates the challenges of parenting, striving to provide the best life for his daughter while dealing with personal struggles. Mrunal Thakur plays the role of the child's mother, bringing emotional depth to the narrative as she supports the father in their shared journey of raising their daughter. The film highlights the joys, sacrifices, and heartwarming moments of family life, focusing on the father's unwavering commitment to his child and the impact of their relationship on his personal growth. With its engaging performances, relatable themes, and touching storyline, Hi Nanna resonates with audiences, capturing the essence of love, family values, and the challenges of parenthood." picURL="./images/hinanna.jpg"></Nani>

      <Nani MovieName="Saripodhaa Sanivaaram" Year="2024" StoryLine="Saripodhaa Sanivaaram (2024) follows Surya Chinnu(Nani), an NLIC agent struggling with significant anger issues stemming from a promise made to his late mother, Chayadevi (Abhirami Gopikumar). She instructed him to channel his anger only on Saturdays, the day she passed away. This peculiar rule leads to conflicts, especially with his elder sister Bhadra (Aditi Balan), who cuts ties with him after a violent incident at her wedding. Years later, Surya's childhood crush, Kalyani Kallu (Priyanka Mohan), returns as PC Charulatha, stirring up unresolved feelings. The oppressive CI R. Dayanand Daya (S. J. Suryah) and his corrupt tactics towards the residents of Sokulapalem intensify the drama. Surya secretly becomes a vigilante on Saturdays, targeting those who wrong him and his community. As he navigates his relationships and the threats posed by Daya and his brother Koormanand (Murali Sharma), Surya's journey leads to a climactic confrontation where he must reconcile his anger with the safety of his loved ones. Ultimately, Surya and Charulatha find love, while Bhadra gives birth to a daughter, marking a significant transformation in their lives." picURL="./images/saripoda.jpg"></Nani>
     
    </div>
  );
}

export default App;
